#!/usr/bin/env python3
"""
Quickly "grep" ansible vault files.

Recursively search current working directory:
vaultgrep "searchterm"

Use some regex for the search query:
vaultgrep "searchterm|anotherterm" /group_vars/all

Recursively search specific directory:
vaultgrep "searchterm" host_vars/myhost
"""
import re
import sys
from pathlib import Path

from ansible import constants as C
from ansible.cli import CLI
from ansible.parsing.dataloader import DataLoader
from ansible.parsing.vault import VaultLib

# Color codes
BGRN = '\033[01;92m'
BRED = '\033[01;31m'
ENDC = '\033[0m'

# First argument is search term
searchterm = sys.argv[1]
rxsearch = re.compile(searchterm)

# Second (optional) argument is path to search
if len(sys.argv) > 2:
    rootdir = Path(sys.argv[2])
else:
    rootdir = Path.cwd()

# Vars for decrypting vault files using Ansible modules
loader = DataLoader()
id_list = C.DEFAULT_VAULT_IDENTITY_LIST
vault_secret = CLI.setup_vault_secrets(loader=loader, vault_ids=id_list)
vault = VaultLib(vault_secret)

def is_vault(file_path):
    """
    Check first line of file for the string '$ANSIBLE_VAULT'

        Parameters:
            file_path (str): File path to search

        Returns:
            bool: True if vault file
    """
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        if '$ANSIBLE_VAULT' in f.readline():
            return True
        return False

# Decrypt vault files
def decrypt(file_path):
    data = vault.decrypt(open(file_path).read())
    data = data.decode("utf-8", errors='ignore').splitlines()
    return data

# Find vault files by parsing the first line of each file
vaultfiles = [str(p) for p in rootdir.rglob('*') if p.is_file() if is_vault(p)]

# Search for word in each vault file
for file in vaultfiles:
    data = decrypt(file)
    found = [x for x in data if rxsearch.search(x)]

    if found:
        print(f"{BGRN}{file}{ENDC}")
        for result in found:
            words = rxsearch.search(result)
            result = rxsearch.sub(f"{BRED}{words[0]}{ENDC}", result)
            result = result.lstrip()
            print(f"  {result}")
        print()

# vim: ft=python ts=4 sts=4 sw=4 sr et
